### ISSUE TITLE
Partition dumping

### ISSUE THREAD

**Issue by Shadowtrance** [d0k3/Decrypt9#14]
Partition dumping doesn't seem to be working on old 3ds via browser (launcher.dat) version. Just sits there at 0%.
Works fine via ninjhax though on both n3ds and o3ds.
Updated my bootstrap branch too. :)
gbatemp not working atm. noooooooo!

**Comment by d0k3** [comment]
Probably already fixed with the last few commits. If not, does it work with Archshifts Decrypt9? Or if you disable TWL decryption?

**Comment by Shadowtrance** [comment]
Still not working via browser. Just sits there at 0% still.
Tried a fresh build from archshift's master branch and partition dumping works from browser.
So something has obviously changed that the browser version doesn't like in regards to partition dumping i guess.

**Comment by d0k3** [comment]
It may be specific to the TWL decryption (because Archshifts branch doesn't have that), but I wonder why... I'm currently working on PRs to Archshifts build, so I have to review all the new code anyways. Let's leave this issue open in the meantime.

**Comment by d0k3** [comment]
Here are two expeimental versions of the launcher.dat. One version removes the work directory (doing everything in root again), the other removes TWL decryption. Link (valid for 7 days):
http://wikisend.com/download/378604/LAUNCHER_DAT_EXPERIMENTAL.zip

Pretty hard to say if we'll find the problem this way. If you get a chance, could you test these?

**Comment by Shadowtrance** [comment]
Tested both, neither of them will actually load. Just sits there white bottom screen, grey top screen.
Don't know what the issue is there.

**Comment by d0k3** [comment]
Strange :/. We'll need to do that differently. The #define for the work directory is in fs.h, and if that is removed, everything will work as normal. The other test will have to wait until we have granular control over NAND partition decryption. By now, I somehow suspect the changed fs functions, but I have no idea why that should work via Brahma and not via Launcher.dat.

**Comment by d0k3** [comment]
Okay, we now have a branch dedicated to fixing this issue:
https://github.com/d0k3/Decrypt9/tree/launcherfix

Even if does not look like it from the changes, this actually reverts more stuff than before. The launcher.dat compiled from the current source is found here:
http://wikisend.com/download/462272/Launcher.dat

If you get a chance, could you give it a try?

**Comment by Shadowtrance** [comment]
Yeah I'll give a test run later (in a couple of hours). Kinda tied up atm.

**Comment by d0k3** [comment]
Alright! Look what I just found:
https://github.com/archshift/Decrypt9/issues/3
Doesn't that sound like our white / gray screen issue?

I'll see if anything is changed for that fix and implement it back again.

**Comment by Shadowtrance** [comment]
Don't know what it is, because if i download your source and build it myself, it runs fine but your compiled versions above don't (grey/white screen issue).
As for the other issues, i built the launcherfix branch myself, it runs. Partition dumping still has the stuck at 0% issue, same with ticket.db (sits there "Searching for ticket.db..." forever). Other testing in progress. No idea what's going on with the launcher.dat version... :(

**Comment by Shadowtrance** [comment]
None of the ticket.db options are working (as mentioned above), NAND backup IS working. And i just compared the start.s from that fixed issue you linked and it matches the one used here (besides some indentation, code matches).

**Comment by d0k3** [comment]
Yeah, I compared it too... if NAND backup works, it is an issue with the crypto functions (NAND backup / restore is the only function that doesn't use crypto functionality). I'll need to think about what could cause this. I'll come up with something.

No idea why my compiled version doesn't work btw, maybe I should update my DevKitPro (though it's fairly recent).

**Comment by d0k3** [comment]
The latest commit to the launcherfix branch may help us find the cause of this problem. It will also break the output of all NAND related functions, but they should at least finish and not be stuck at 0%. It would also be interesting if non-NAND related stuff (ncch xorpad generating and titlekey decryption form file) work.

If I prove right with that, it is bad, and we may never have a launcher.dat version that decrypts the TWL.

**Comment by Shadowtrance** [comment]
Partition dumping is working with the latest change, well it isn't stuck at 0% doing nothing. Well... it completed successfully, but they appear to be still encrypted.
I tested ticket.db dumping as well, failed straight away.

**Comment by d0k3** [comment]
Yup, that's what I expected, and we got the reason for the freeze now. The access to memory region 0x01FFCD80 (ie. the NAND CID). Good that we found it, but dammit... we need that access for TWL decryption. I'll try to figure out how to enable this for the launcher.dat, but I'm unsure if it is possibly at all.

**Comment by d0k3** [comment]
Okay, the last commit is based on some kind of elaborated guess. It might give back the NAND CID access to Launcher.dat, it might also crash again. If you've got some time, you could try it, or wait until I at least tried to come up with something better.

**Comment by Shadowtrance** [comment]
Yeah I'll give it a go in a minute. :)

**Comment by Shadowtrance** [comment]
Nope... no go. :( ticket.db searches forever like before, partition dumping sits there at 0%.

**Comment by d0k3** [comment]
Okay, alright. Maybe the experts know something. We've got the reason now and we know what needs to be fixed. Leaving that open for now...

**Comment by Shadowtrance** [comment]
I guess we can close this now. :)
